Added more info about the user to the avatar menu
google/if-this-then-ad pull request #39
Opened 2022-02-25 10:20 UTC by akushnarov

2022-02-25 13:06 UTC, paranerd requested changes

2022-02-25 13:06 UTC, paranerd commented on client/src/app/components/header/header.component.html
> +    <div class="avatar-wrapper avatar-wrapper-padding" *ngIf="user">
Maybe instead of checking `*ngIf="user"` three times here, we could add it to L36 (or create a container right underneath?

2022-02-25 13:06 UTC, paranerd commented on client/src/app/components/header/header.component.html
> +    <div *ngIf="user" class="avatar" [style.backgroundImage]="'url(' + user.profilePhoto + ')'"></div>
Great decision!

2022-03-08 12:37 UTC, maxkimambo approved these changes
LGTM

2022-03-09 11:48 UTC, merged